name: FRONT

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_PROJECT_NAME}}:piscine

  redeploy:
    needs: build
    name: Redeploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd PiscineMadness/
            docker compose pull 
            docker compose up -d
            docker image prune -f